/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5vCpJAHkMod
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import Link from "next/link"

export function Component() {
  return (
    <section className="w-full pt-12 md:pt-24 lg:pt-32">
      <div className="container space-y-10 xl:space-y-16">
        <Carousel className="w-full max-w-5xl mx-auto">
          <CarouselContent>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                width={1200}
                height={675}
                alt="Hero Image 2"
                className="aspect-video object-cover rounded-lg"
              />
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                width={1200}
                height={675}
                alt="Hero Image 4"
                className="aspect-video object-cover rounded-lg"
              />
              <div className="flex-1 bg-black/70 group-hover:opacity-90 transition-opacity text-white p-10 justify-end flex flex-col gap-2">
                <h3 className="font-semibold text-lg tracking-tight text-center">Create Events</h3>
              </div>
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                width={1200}
                height={675}
                alt="Hero Image 5"
                className="aspect-video object-cover rounded-lg"
              />
              <div className="flex-1 bg-black/70 group-hover:opacity-90 transition-opacity text-white p-10 justify-end flex flex-col gap-2">
                <h3 className="font-semibold text-lg tracking-tight text-center">Create Events</h3>
              </div>
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                width={1200}
                height={675}
                alt="Hero Image 6"
                className="aspect-video object-cover rounded-lg"
              />
              <div className="flex-1 bg-black/70 group-hover:opacity-90 transition-opacity text-white p-10 justify-end flex flex-col gap-2">
                <h3 className="font-semibold text-lg tracking-tight text-center">Search Events by Location</h3>
              </div>
            </CarouselItem>
          </CarouselContent>
          <CarouselPrevious className="absolute left-4 top-1/2 -translate-y-1/2 z-10 rounded-full bg-background/50 p-2 text-primary-foreground hover:bg-background/75 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
            <ChevronLeftIcon className="h-6 w-6" />
            <span className="sr-only">Previous</span>
          </CarouselPrevious>
          <CarouselNext className="absolute right-4 top-1/2 -translate-y-1/2 z-10 rounded-full bg-background/50 p-2 text-primary-foreground hover:bg-background/75 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring">
            <ChevronRightIcon className="h-6 w-6" />
            <span className="sr-only">Next</span>
          </CarouselNext>
        </Carousel>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 md:gap-8">
          <div className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">Create Events</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Create Events"
              width={400}
              height={400}
              className="[grid-area:stack] object-cover w-full aspect-square"
            />
            <div className="flex-1 [grid-area:stack] bg-black/70 group-hover:opacity-90 transition-opacity text-white p-10 justify-end flex flex-col gap-2">
              <h3 className="font-semibold text-lg tracking-tight text-center">Create Events</h3>
            </div>
          </div>
          <div className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">Create Events</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Create Events"
              width={400}
              height={400}
              className="[grid-area:stack] object-cover w-full aspect-square"
            />
            <div className="flex-1 [grid-area:stack] bg-black/70 group-hover:opacity-90 transition-opacity text-white p-10 justify-end flex flex-col gap-2">
              <h3 className="font-semibold text-lg tracking-tight text-center">Create Events</h3>
            </div>
          </div>
          <div className="relative group grid [grid-template-areas:stack] overflow-hidden rounded-lg">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">Search Events by Location</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Search Events by Location"
              width={400}
              height={400}
              className="[grid-area:stack] object-cover w-full aspect-square"
            />
            <div className="flex-1 [grid-area:stack] bg-black/70 group-hover:opacity-90 transition-opacity text-white p-10 justify-end flex flex-col gap-2">
              <h3 className="font-semibold text-lg tracking-tight text-center">Search Events by Location</h3>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
